# For more information see: https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-maven

name: Maven PRB

on:
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: Set up JDK
        uses: actions/setup-java@v2
        with:
          java-version: 17
          distribution: 'zulu'
          cache: 'maven'
      - name: Build with Maven
        run: mvn -B -V -Dstyle.color=always clean verify
      - name: Test & publish code coverage
        uses: paambaati/codeclimate-action@v3.0.0
        env:
          CC_TEST_REPORTER_ID: ${{secrets.CC_TEST_REPORTER_ID}}
          # Action does not support globbing for this environment variable.
          # This can be formatted as a list with whitespace (" ") delimiter.
          JACOCO_SOURCE_PATH: ${{github.workspace}}/2020/src/main/java
        with:
          coverageCommand: mvn -B -V -Dstyle.color=always verify -Pcoverage
          # Action supports globbing for these locations, so "**" should cover any (sub-)module.
          coverageLocations: ${{github.workspace}}/**/target/site/jacoco/jacoco.xml:jacoco
